spring:
  datasource:
    url: jdbc:postgresql://192.168.1.15:5432/cursoSpring
    username: postgres
    password: gocrowd
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
server: 
  port: 8080
