spring:
  datasource:
    url: jdbc:postgresql://85.56.26.179:5432/cursoSpring
    username: postgres
    password: gocrowd
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
eureka:
  client:
    serviceUrl:
      defaultZone: http://85.56.26.179:8761/eureka
  instance:
    instance-id: instancia1
server: 
  port: 8080
