spring:
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/cursoSpring
    username: postgres
    password: gocrowd
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka
  instance:
    instanceId: instancia-hotel
server: 
  port: 8080
