spring:
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/cursoSpring
    username: postgres
    password: gocrowd
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka
  instance:
    instanceId: instancia-reserva
    hostName: http://172.21.32.1
server: 
  port: 8082
hotel:
  url: http://servicio-hotel/hotel
vuelo:
  url: http://servicio-vuelo/vuelo
