spring:
  datasource:
    url: jdbc:postgresql://postgres-db:5432/db
    username: postgres
    password: gocrowd
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka
  instance:
    instanceId: instancia-reserva
server: 
  port: 8082
hotel:
  url: http://servicio-hotel/hotel
vuelo:
  url: http://servicio-vuelo/vuelo
