spring:
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/cursoSpring
    username: postgres
    password: gocrowd
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
eureka:
  client:
    serviceUrl:
      defaultZone: http://host.docker.internal:8761/eureka
    instance:
      instance-id: instancia-reserva
server: 
  port: 8082
hotel:
  url: http://servicio-hotel/hotel
vuelo:
  url: http://servicio-vuelo/vuelo
